### ISSUE TITLE
landmark detection訓練的問題

### ISSUE THREAD

**Issue by DLnovice** [AITTSMD/MTCNN-Tensorflow#100]
您好 : 
請問我如果只想做face detection的部分,不想做landmark detection,那麼我要刪的部分是不是就是mtcnn_model與train裡landmark的相關資訊呢?或是有甚麼是需要注意的嗎?
因為我怕刪到不該刪的.
謝謝

**Comment by AITTSMD** [comment]
@DLnovice 修改网络结构；修改输入shape；重新生成tfrecord，移除landmark部分；

**Comment by DLnovice** [comment]
請問關於"修改輸入shape"的部分要在哪個環節處理呢?
