### ISSUE TITLE
landmark准确率不太高，是因为训练集的原因吗？

### ISSUE THREAD

**Issue by xzzhh789** [AITTSMD/MTCNN-Tensorflow#107]

**Comment by xzzhh789** [comment]
您好，最近跑了您的代码，发现最后对人脸的特征点检测似乎不是很准确，眼睛位置明显偏上一点，请问这是因为landmark训练集的原因吗？

**Comment by AITTSMD** [comment]
@xzzhh789 嗯，有可能，因为特征点部分训练用的数据集太少了，你可以换个数据集试试，还有做数据增强的时候，注意特征点位置是否要做对应的改变。
