### ISSUE TITLE
Segmentation fault 错误 在生成tfrecord时候报错

### ISSUE THREAD

**Issue by cnzdc** [AITTSMD/MTCNN-Tensorflow#109]
>>>>>> Start tfrecord create...Stage: rnet
Converting[rnet]: 138401/138483Segmentation fault
具体原因是什么呢？

**Comment by AITTSMD** [comment]
@cnzdc 可能是内存溢出，具体原因我也不太清楚，可以参考https://github.com/AITTSMD/MTCNN-Tensorflow/issues/14

**Comment by AITTSMD** [comment]
@Edwardmark 谢谢回答
