### ISSUE TITLE
What is the purpose of that calculation?

### ISSUE THREAD

**Issue by xav12358** [AITTSMD/MTCNN-Tensorflow#110]
Hello,

I try to understand the generateBoundingBox function. I don't really understand some lines:
`    bb = np.transpose(np.vstack([y, x]))
    q1 = np.fix((stride * bb + 1) / scale)
    q2 = np.fix((stride * bb + cellsize - 1 + 1) / scale)
`

What are q1,q2 stride and cellsize?

**Comment by AITTSMD** [comment]
@xav12358 stride means total stride in the network, cellsize means input size in the network. q1  and q2 are the bbox's position  in original image.
