### ISSUE TITLE
issue with training Face Landmark Detection.

### ISSUE THREAD

**Issue by rashmisgh** [AITTSMD/MTCNN-Tensorflow#115]
Hey, please help me with this, I get this problem while running gen_landmark_aug_12.py.
File "gen_landmark_aug_12.py", line 180, in 
imgs,landmarks = GenerateData(train_txt, OUTPUT,net,argument=True)
File "gen_landmark_aug_12.py", line 67, in GenerateData
assert(img is not None)
AssertionError
please solve this issue
Thank you.

**Comment by AITTSMD** [comment]
@rashmisgh check images' path!

**Comment by rashmisgh** [comment]
I have checked the images path as you have asked to unzip the train.zip file in prepare_data its there with lfw_5590 and net_7876.

**Comment by rashmisgh** [comment]
Thank you very much I have resolved the issue thanks a lot.
The issue was with image path, we have to change '/' with '\'.
