### ISSUE TITLE
gen_12net_data.py有点看不明白

### ISSUE THREAD

**Issue by Edwardmark** [AITTSMD/MTCNN-Tensorflow#116]
67行已经生成过50张负样本了：  
https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_12net_data.py#L67  
为何在102行又生成5张负样本：    
https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_12net_data.py#L102  
这两处的代码貌似没什么区别啊？

**Comment by Dugudaibo** [comment]
我也有同样的问题。但是我推测可能是作者希望有那种包含 bounding box  @但还是负样本的数据吧，希望得到作者的解答/

但是我还有另外一个问题，就是按照这个文件所产生的数据不能够满足论文中3：1：1的要求

**Comment by jjrCN** [comment]
在gen_imglist_pnet.py中生成1:1:1:3的代码，并非生成的全部使用。

**Comment by Dugudaibo** [comment]
哦哦对的，想起来了，十分感谢

但是生成的landmark的数据比例是2吗？

**Comment by jjrCN** [comment]
按作者提供的数据集来landmark最后大概是17万左右我记得，然后pos设置的是25万，勉强是1:1。如果我没记错的话。。

**Comment by jjrCN** [comment]
这个我也不清楚了，我自己的路径也是修改过的。。=，=

**Comment by Dugudaibo** [comment]
嗯嗯没事，我已经找到原因了~就在我提的那个问题里面自问自答了
但是也很谢谢你啦~~~

**Comment by Dugudaibo** [comment]
嗯嗯没事，我已经找到原因了就在我提的那个问题里面自问自答了
但是也很谢谢你啦
