### ISSUE TITLE
训练过程中显示没有这个文件

### ISSUE THREAD

**Issue by Dugudaibo** [AITTSMD/MTCNN-Tensorflow#117]
我在执行  `python gen_imglist_rnet.py`的时候出现如下报错
No such file or directory: './24/pos_24.txt'
我发现在12有对应的文件，但是在24找不到对应的文件

**Comment by Dugudaibo** [comment]
已经发现这个问题的解决办法了，是自己没有仔细阅读代码，在`python gen_hard_example.py`中line 215 中将 onet 改为 pnet即可。

**Comment by Dugudaibo** [comment]
错了错了，改成RNet

**Comment by rain2008204** [comment]
@Dugudaibo 改完后就可以了吗

**Comment by Dugudaibo** [comment]
对的

**Comment by rain2008204** [comment]
@Dugudaibo 我修改完了，但是在运行Run gen_imglist_rnet.py to merge two parts of training data. 这一步是，还是提示No such file or directory: './24/pos_24.txt'在24找不到对应的文件，24下面的东西是空的，你能把你修改的源码发到我邮箱吗？fanjihui2008@126.com
