### ISSUE TITLE
用caffe训练，误检较多

### ISSUE THREAD

**Issue by stone226** [AITTSMD/MTCNN-Tensorflow#119]
我用caffe训练的，暂时没有关键点任务，也没ohme.训练比例1:1:3（pos,part,neg），训练后，三个网络的准确率在92 93 95 左右，网络收敛。
问题
1 测试发现最后误检较多。
2 用pnet生成hard样本的时候，发现只能有2w左右的pos生成（与你的14w，差异很大）；于是，我在训练rnet的时候是按照类似前面直接随机裁剪的方式生成的正样本，负样本是用pnet检测生成的。另外，我特意用原作者开放的模型，用它的pnet,发现也只有2w左右的pos生成。
3 目前，我对比，与你做样本的方式是一样，采用的也是同样数据集（widerface）。区别是，我没做关键点任务，ohem,l2loss,但这些应该不会影响很大。
求建议。

**Comment by stone226** [comment]
@chiukeung 只参考了一部分，但没用其中的pythonlayer.方便加我Q吗 1589735919 交流下

**Comment by AITTSMD** [comment]
@stone226 @chiukeung 我之前用caffe复现mtcnn时，就发现产生的正样本数目很少，召回率很低，一直没找到原因，所以才换成TensorFlow了。

**Comment by grainw** [comment]
@AITTSMD  能提供下用caffe 复现mtcnn 的代码吗？一直没找到一个合适的项目用caffe 训练mtcnn，总是走不通
