### ISSUE TITLE
Inconsistency with orinal article

### ISSUE THREAD

**Issue by ilyanelken** [AITTSMD/MTCNN-Tensorflow#12]
Hi @AITTSMD ,

Thanks for Tensor-Flow implementation.

In:
https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/train_models/train.py#L135

the landmark loss ratio is 1.0 although in original article it is 0.5.
Is there a special reason for that?

Thanks,
Ilya

**Comment by ilyanelken** [comment]
@AITTSMD An additional question: how is sample type beta that is mentioned in original article is handled in overall learning target?

**Comment by AITTSMD** [comment]
@ilyanelken  sorry，No  special reason！Just my fault.

**Comment by ilyanelken** [comment]
@AITTSMD cool, thanks! I have seen you have fixed it.
