### ISSUE TITLE
请问下rnet在fddb下的召回率

### ISSUE THREAD

**Issue by dl8207531** [AITTSMD/MTCNN-Tensorflow#123]
我这边测出来的为92%左右，pnet为98%，相对来看rnet下降很多，请问这是否正常，你测出来的为多少？

**Comment by AITTSMD** [comment]
@dl8207531 嗯，rnet的召回率是会低于pnet，因为经过一次过滤。我的大概是94%。

**Comment by jhgfkdj** [comment]
请问一下作者给出的代码中有没有fddb召回率的检测代码？否则请问一下哪里有fddb测试集召回率的测试代码？谢谢！

**Comment by dl8207531** [comment]
检测倒不难检测图和数据集做iou，记录大于0.65数量除以总数量
