### ISSUE TITLE
wider_face_train.txt

### ISSUE THREAD

**Issue by rashmisgh** [AITTSMD/MTCNN-Tensorflow#124]
How did you get these file wider_face_train.txt and wider_face_train_bbx_gt.txt? If I want to train Mtcnn on my own data set how will I get these file?

**Comment by jetta** [comment]
Read README first.

`You should first download WIDER Face and Celeba.WIDER Face for face detection and Celeba for landmark detection(This is required by original paper.But I found some labels were wrong in Celeba. So I use this dataset for landmark detection).`

**Comment by rashmisgh** [comment]
I want to train on my own data set. what will be the steps to get that .txt file?

**Comment by AITTSMD** [comment]
@rashmisgh you can directly use wider_face_train.txt, just to change the code for reading annotation.

**Comment by zhulihuacmss** [comment]
@rashmisgh if you want to train on your own data,  i think you first need to label many images to get that .txt file. WIDER Face is an open dataset and has been labeled so you need to label you own data before you train you own model.
