### ISSUE TITLE
landmark loss值问题请教

### ISSUE THREAD

**Issue by jetta** [AITTSMD/MTCNN-Tensorflow#125]
根据函数`landmark_ohem`的实现，如果整个batch里没有`label`为`-2`的样本，那么`landmark loss` 的输出为nan，难道不是应该为0么？
谢谢！

**Comment by AITTSMD** [comment]
@jetta 我的batch一定有landmark部分的，你是把landmark部分去掉了吗？

**Comment by stupiding** [comment]
> @jetta 我的batch一定有landmark部分的，你是把landmark部分去掉了吗？

请问您是怎么保证每个batch都有landmark的？我在数据制作的代码中没看到相关处理，不知道是不是在其他地方?
