### ISSUE TITLE
关于train_PNet的问题

### ISSUE THREAD

**Issue by moonyoung430** [AITTSMD/MTCNN-Tensorflow#126]
@AITTSMD 你好，非常感谢您所作的这项工作，非常有意义！
我跟着readme的prepare data步骤一直到步骤7，看到步骤7在run gen_hard_example之前需要先train PNet，在代码里应该是直接调用了data里预训练的模型对吧，但我想自己尝试训练PNet，是不是就用train_model里的train_PNet.py？我运行的时候发现这个脚本里 from read_tfrecord_v2 import 。。。这个read_tfrecord_v2没有啊，找不到啊。
不知道是否我哪里搞错了

**Comment by jetta** [comment]
`prepare_data`目录下`read_tfrecord_v2.py`

**Comment by moonyoung430** [comment]
@jetta  非常感谢，我之前没有看到～～～
另外我想再确认一下，如果自己训练PNet的话是 运行 train_PNet就行吗？
还有 整个prepare data的过程结束后，还要做什么来训练及测试模型呢？

不好意思问了这么多～艰难的啃代码中。。。

**Comment by jetta** [comment]
@moonyoung430 看看README里的`Prepare For Training Data`

**Comment by moonyoung430** [comment]
@jetta Prepare For Training Data里的步骤我理解是为训练准备数据的过程啊，只训练了PNet和RNet，最后的ONet 是要自己训练的吧。
