### ISSUE TITLE
运行gen_RNet_tfrecords.py时出现Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by L1xiaolong** [AITTSMD/MTCNN-Tensorflow#128]
您好，感谢您分享源码。
我在尝试复现您的工程时，运行gen_RNet_tfrecords.py时出现以下现象：
Process finished with exit code -1073741819 (0xC0000005)
请问这是什么原因呢？有没有解决方法？
非常感谢！

**Comment by MrLeeBin93** [comment]
remove the line "tfrecord_writer.close()" and then you can use 'for item in ['landmark', 'pos', 'part', 'neg']' run， instead of running four time of gen_hard_example.py
