### ISSUE TITLE
使用Hardsample生成的时候负样本数量非常庞大

### ISSUE THREAD

**Issue by yungs2017** [AITTSMD/MTCNN-Tensorflow#13]
在生成RNet的数据时候，每张图片平均需要执行的时间为1~5分钟，生成的负样本巨大，打印出来的信息显示模型识别出来的ROI数量太大，是否是模型的准确率不好导致？

**Comment by AITTSMD** [comment]
@yungs2017 你训练Pnet的准确率大概多少？可以将Pnet用于人脸检测，观察一下，看看人脸是否被框到了
