### ISSUE TITLE
运行train_ONet.py时，到coord.join(threads)出错

### ISSUE THREAD

**Issue by liuyunwww** [AITTSMD/MTCNN-Tensorflow#131]
谢谢你的分享！
运行你的程序，终于走到train_ONet.py，却被卡在这了！

使用的是笔记本电脑，CPU
数据不包含landmark

错误提示：
.......
(320, 48, 48, 3)
(320,)
(320, 4)
(320, 10)
1.0
[-0.01 -0.    0.06  0.2 ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2786
Traceback (most recent call last):
  File "train_models/train_ONet.py", line 30, in <module>
    train_ONet(base_dir, prefix, end_epoch, display, lr)
  File "train_models/train_ONet.py", line 18, in train_ONet
    train(net_factory, prefix, end_epoch, base_dir, display=display, baseLr=lr,
gpus='0')
  File "E:\Software\TensorFlow\mtcnn_tf-master\train_models\train.py", line 196,
 in train
    coord.join(threads)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\trainin
g\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\six.py", line 693, in rer
aise
    raise value
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\trainin
g\queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 1249, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framewo
rk\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 37853
32433
         [[Node: ReaderReadV2_2 = ReaderReadV2[_device="/job:localhost/replica:0
/task:0/device:CPU:0"](TFRecordReaderV2_2, input_producer_2)]]

**Comment by Dugudaibo** [comment]
您好，我在运行 train_RNet 的过程中遇到了问题，就是 loss 一直是-0.000000，然后他的正确率一直是一个0.72……的常数，不知道您有没有遇到过这个问题~

**Comment by liuyunwww** [comment]
不好意思，没有碰到。

**Comment by Dugudaibo** [comment]
请问您的landmark的数据用的是开源作者的数据集，还是用的celeba~

**Comment by liuyunwww** [comment]
@AITTSMD 
能帮忙看一下为什么会运行到coord.join(threads)出错。

**Comment by AITTSMD** [comment]
@liuyunwww 参考https://github.com/tensorflow/models/issues/571一下，多半是数据准备有误。

**Comment by AITTSMD** [comment]
@liuyunwww 参考 https://github.com/tensorflow/models/issues/571

**Comment by liuyunwww** [comment]
非常感谢你的回复。
前一段时间忙于考试，没有继续调试程序。
有可能是你说的数据的问题，因为我在分别运行gen_RNet_tfrecords.py时（pos 1527，part 19883，neg 520780），运行到>> Converting image 520780/520780--- 24\negative\3305.jpg
会弹出对话框说，Python已停止工作。
我检查了一下，是tfrecord_writer.close()出错。
pos和part不会弹出对话框，但在最后没有看到Finished converting the MTCNN dataset!

我没有针对landmark运行，因为我的数据不包含。

**Comment by liuyunwww** [comment]
非常感谢你的回复。
前一段时间忙于考试，没有继续调试程序。
有可能是你说的数据的问题，因为我在分别运行gen_RNet_tfrecords.py时（pos 1527，part 19883，neg 520780），运行到>> Converting image 520780/520780--- 24\negative\3305.jpg
会弹出对话框说，Python已停止工作。
我检查了一下，是tfrecord_writer.close()出错。
pos和part不会弹出对话框，但在最后没有看到Finished converting the MTCNN dataset!

我没有针对landmark运行，因为我的数据不包含。

**Comment by liuyunwww** [comment]
@AITTSMD

**Comment by liuyunwww** [comment]
运行python one_image_test.py
WARNING:tensorflow:From E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflo
w\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contri
b.learn.python.learn.datasets.base) is deprecated and will be removed in a futur
e version.
Instructions for updating:
Use the retry module or similar alternatives.
(1, ?, ?, 3)
(1, ?, ?, 10)
(1, ?, ?, 10)
(1, ?, ?, 16)
(1, ?, ?, 32)
(1, ?, ?, 2)
(1, ?, ?, 4)
(1, ?, ?, 10)
./data/MTCNN_model/PNet_landmark
(256, 24, 24, 3)
(256, 22, 22, 28)
(256, 11, 11, 28)
(256, 9, 9, 48)
(256, 4, 4, 48)
(256, 3, 3, 64)
(256, 576)
(256, 128)
(256, 2)
(256, 4)
(256, 10)
lala\1.jpg
lala\1.jpg
0 images done
[4.9612436e-06 2.2406735e-14 1.9195245e-06]
lala\1.jpg

1.jpg上没有显示检测到的bbox

**Comment by liuyunwww** [comment]
tfrecord_writer.close()出错的问题，在
https://github.com/AITTSMD/MTCNN-Tensorflow/issues/14
有解释

**Comment by liuyunwww** [comment]
tfrecord_writer.close()出错的问题，在
https://github.com/AITTSMD/MTCNN-Tensorflow/issues/14
有解释
