### ISSUE TITLE
按步骤运行难例时出现了问题

### ISSUE THREAD

**Issue by jhgfkdj** [AITTSMD/MTCNN-Tensorflow#132]
请问一下，我训练完PNet后按步骤就跑hard example了，但是报错NotFoundError (see above for traceback): Key fc1/alphas not found in checkpoint……凭感觉是不是哪里的参数设置有点问题，还是图建跟训练的图有问题？请教一下了。

**Comment by liuyunwww** [comment]
前面有人提出这个问题。

**Comment by jhgfkdj** [comment]
@liuyunwww 你好，不知你有没有碰到了这个问题？按照那贴提供的解决办法，一是换tf版本，这个我想之后再试，何况只能用1.2版本的话那还是有点局限了。二是改变模型代码中的全连接层去掉激活函数参数，但是这样子的话岂不是要重新训练了吗？看回复帖子里的意思是改了之后就可以直接跑hard example了？那我还是没跑起来……

**Comment by jhgfkdj** [comment]
@liuyunwww 你是在刚好1.2的版本下训练的吗？我高版本的只有1.4的tf了，不知道训练完后是不是可以跑得起来……

**Comment by liuyunwww** [comment]
1.7.0

**Comment by AITTSMD** [comment]
@jhgfkdj @liuyunwww 跟tf版本关系不大，refer #30 ，直接把全连接的激活函数由prelu 改成 relu就可以刻

**Comment by jhgfkdj** [comment]
@AITTSMD 谢谢，按你说的修改并重新训练后成功跑通了……
