### ISSUE TITLE
训练标签问题

### ISSUE THREAD

**Issue by DLnovice** [AITTSMD/MTCNN-Tensorflow#134]
您好：
在 Prepare For Training Data 中的 gen_12net_data.py 用的标签是 wide_face_train.txt，但是在 
gen_hard_example.py 中用的标签是 wider_face_train_bbx_gt.txt ，我想要请问如果我想要全部都只用 wide_face_train.txt的话，要怎么改呢？让我在跑 gen_hard_example.py 时读 wide_face_train.txt标签就好。这样就不用分两个版本的标签了，　谢谢!

**Comment by AITTSMD** [comment]
@DLnovice 只是修改读取注释文件部分的代码就可以，
