### ISSUE TITLE
为何只在PNet中使用1x1卷积代替全连接？而不再RNet和ONet中使用1x1卷积呢？

### ISSUE THREAD

**Issue by Edwardmark** [AITTSMD/MTCNN-Tensorflow#136]

**Comment by kingrain213** [comment]
只是粗略的计算个结果出来，减少参数和计算量？

**Comment by Edwardmark** [comment]
@kingrain213 不是吧，计算量是一样的

**Comment by choice17** [comment]
@Edwardmark, PNet does not use fully connected layer, as input of PNet is a image without fixed resolution which allows dynamic input and output resolution while RNet, ONet need fixed size input (24x24x3 and 48x48x3), you may read https://kpzhang93.github.io/MTCNN_face_detection_alignment/index.html matlab codes for details.

**Comment by Edwardmark** [comment]
@choice17 Thanks man.
