### ISSUE TITLE
landmarks of flipped face

### ISSUE THREAD

**Issue by zhangxw87** [AITTSMD/MTCNN-Tensorflow#137]
In  https://github.com/AITTSMD/MTCNN-Tensorflow/blob/4437e8eb47db3b3886eeb7967f1520c0599dbc11/prepare_data/Landmark_utils.py#L52, what's the purpose of computing 1-x? Since the input landmarks are offsets, I think computing -x should be right. Correct me if I am wrong.

**Comment by AITTSMD** [comment]
@zhangxw87 When we do mirror to conduct data augmentation, all key points' coordinate should be changed correspondingly. Draw it then you can get it.
