### ISSUE TITLE
Test on batch

### ISSUE THREAD

**Issue by najeeb-tyson** [AITTSMD/MTCNN-Tensorflow#139]
I want to test detection on batch of images. By using _test/one_image_test.py_ file how to test on batches.

**Comment by AITTSMD** [comment]
@najeeb-tyson Hi, just use some images to contruct a mini-batch(you can use an array to represent it, resize the images to the same size), then forword.You shoud pay attention to the dimension of the input data.

**Comment by najeeb-tyson** [comment]
@AITTSMD  yes I have done that but the problem is _Detection/MtcnnDetector.py's_ functions _detect_pnet_ , _detect_rnet_ and _detect_onet_ all accepting sigle image. 
for example: 
`def detect_pnet(self, im): `
**`       h, w, c = im.shape`**
`        net_size = 12`

**Comment by AITTSMD** [comment]
@najeeb-tyson Then you should change the source code.
