### ISSUE TITLE
fail to make tfrecord 

### ISSUE THREAD

**Issue by flankechen** [AITTSMD/MTCNN-Tensorflow#14]
I just go through preparing data step until step 6:Run gen_PNet_tfrecords.py to generate tfrecord for PNet.
a Segmentation fault (core dumped) error after some long logs of running.

>> Converting image 1437679/1437687('---', '12/positive/67987.jpg')
>> Converting image 1437680/1437687('---', '12/train_PNet_landmark_aug/97899.jpg')
>> Converting image 1437681/1437687('---', '12/positive/36229.jpg')
>> Converting image 1437682/1437687('---', '12/positive/173181.jpg')
>> Converting image 1437683/1437687('---', '12/train_PNet_landmark_aug/172922.jpg')
>> Converting image 1437684/1437687('---', '12/positive/15968.jpg')
>> Converting image 1437685/1437687('---', '12/positive/71556.jpg')
>> Converting image 1437686/1437687('---', '12/negative/709222.jpg')
>> Converting image 1437687/1437687('---', '12/negative/18498.jpg')
Segmentation fault (core dumped)

I check that image, looks ok.

**Comment by flankechen** [comment]
@AITTSMD I think so, different run of the code crash in different image. but I am runing this on a desktop with 32G ram and a gtx1080 GPU. Do I have to set the terminal or python or tensorflow something to unlimiti the usage of memory? thanks

**Comment by flankechen** [comment]
after few days calm down, I found that the loop actually gothrough all the images and get this segmentation fault crash in tfrecord_writer.close(), which I might consider something wrong with my tensorflow environment. Anyway, it do generat the tfrecord. and I can go to next step.

Thanks a lot and I am closing this.

**Comment by BigBang0072** [comment]
Is it happening after completing all the image conversion to tfrecords? 
For me, it was coming since I was not closing the writer properly. Using the writer in a with
block solved the problem.
