### ISSUE TITLE
Nameerror: global name “O_Net” is not defined

### ISSUE THREAD

**Issue by chaowang1994** [AITTSMD/MTCNN-Tensorflow#146]
你好，为了运行：

> After training RNet, run gen_hard_example to generate training data(Face Detection Part) for ONet.

我把 [gen_hard_example.py](https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_hard_example.py#L189) 修改为

parser.add_argument('--test_mode', dest='test_mode', help='test net type, can be pnet, rnet or onet',
                        default='ONet', type=str), 即把default='RNet'==》default='ONet'
但训练过程出现了

> Nameerror: global name “O_Net” is not defined

貌似是你在from train_models.mtcnn_model import P_Net,R_Net 并没有import O_Net
这改怎么改啊？谢谢

**Comment by AITTSMD** [comment]
@chaowang1994 gen_hard_example.py是用来产生困难样本的，运行PNet会产生RNet的训练样本，运行RNet产生ONet的训练样本，不需要运行ONet产生训练样本。
