### ISSUE TITLE
求助：gen_hard_example.py生成RNET的数据里正样本非常少

### ISSUE THREAD

**Issue by qinhui99** [AITTSMD/MTCNN-Tensorflow#148]
我对PNET做了一些改动，训练出来的PNET准确率95.3%. 可是用95.3%的PNET模型生成的RNET数量里，正样本数量只有可怜的200多个，负样本有几百万个。 是我遗漏了什么重要的内容吗？

**Comment by AITTSMD** [comment]
@qinhui99 检查一下你设置的参数，看看是否是判断人脸阈值过高。最好把PNET的结果可视化出来，看看是否人脸部分全部被框起来。

**Comment by winter-solider** [comment]
我在对三个阶段生成的样本分析了，查看了一下生成的图片，12net里面的part 部分有很多是完整的人脸，24net和48net 的part部分也有很多是完整的人脸。不算是部分人脸，neg部分在训练的时候和landmark部分的人脸一样都是label=0, 这样会不会对训练造成影响呢

**Comment by qinhui99** [comment]
我用的是gen_hard_example.py默认的阈值：default=[0.4, 0.05, 0.7]，应该不会太高。另外，PNET的结果可视化可以用test/one_image_test.py来做吧？ 明天我试试可视化一些图片看看。

**Comment by qinhui99** [comment]
找到问题了。是我实现了对权重的二值量化的函数与mtcnn实现不太兼容。加了这个二值化函数，准确率看起来只下降了一点点，但是生成RNET的数据里的正样本数量会大幅下降。把它注释掉后，正样本数量就恢复正常了。
