### ISSUE TITLE
Unable to download landmark training data

### ISSUE THREAD

**Issue by siffi26** [AITTSMD/MTCNN-Tensorflow#149]
In the README.md, Point No. 2, under "Prepare For Training Data", there is no link present to download.

**Comment by AITTSMD** [comment]
@siffi26 refer http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm

**Comment by nihilityworld** [comment]
你好 我想问一下这个数据库的格式是什么啊 x y  w h pointx pointy 这样的吗
