### ISSUE TITLE
gen_RNet_tfrecords.py 怎么运行四次啊？

### ISSUE THREAD

**Issue by chaowang1994** [AITTSMD/MTCNN-Tensorflow#150]
步骤10.Run gen_RNet_tfrecords.py to generate tfrecords for RNet.(you should run this script four times to generate tfrecords of neg,pos,part and landmark respectively)
和步骤14.
按照之前的[issue 3](https://github.com/AITTSMD/MTCNN-Tensorflow/issues/3)  的解决办法，但代码里并没有

> #return '%s/landmark_landmark.tfrecord' % (output_dir)    	#if you want to generate landmark_landmark tfrecord,uncomment this line.
> #return '%s/pos_landmark.tfrecord' % (output_dir)	      #if you want to generate pos_landmark tfrecord,uncomment this line.
> #return '%s/neg_landmark.tfrecord' % (output_dir)	      #if you want to generate neg_landmark tfrecord,uncomment this line.
> return '%s/part_landmark.tfrecord' % (output_dir)	      #if you want to generate part_landmark tfrecord,uncomment this line.
> 
这些啊，请问应该怎么修改啊

**Comment by Huanyongji** [comment]
@chaowang1994 https://github.com/AITTSMD/MTCNN-Tensorflow/issues/1

**Comment by Huanyongji** [comment]
@chaowang1994 第一个问题已经提到过了，查看一下吧

**Comment by chaowang1994** [comment]
谢谢~·
修改gen_RNet_tfrecords.py 和 gen_ONet_tfrecords.py里相应的函数修改为下面的代码：
def get_dataset(dir, net):
#item = 'imglists/PNet/train_%s_raw.txt' % net
#item = 'imglists/PNet/train_%s_landmark.txt' % net
#------uncomment below four line to generate four tfrecords for training RNet---------
#item = '%s/landmark_%s_aug.txt' % (net,net) #if you want to generate landmark_landmark tfrecord,uncomment this line.
#item = '%s/pos_%s.txt' % (net,net) #if you want to generate pos_landmark tfrecord,uncomment this line.
#item = '%s/neg_%s.txt' % (net,net) #if you want to generate neg_landmark tfrecord,uncomment this line.
item = '%s/part_%s.txt' % (net,net) #if you want to generate part_landmark tfrecord,uncomment this line.

def get_output_filename(output_dir, name, net):
#st = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
#return '%s/%s%s_%s.tfrecord' % (output_dir, name, net, st)
#return '%s/train_PNet_landmark.tfrecord' % (output_dir)

#------uncomment below four line to generate four tfrecords for training RNet---------
#return '%s/landmark_landmark.tfrecord' % (output_dir)    	#if you want to generate landmark_landmark tfrecord,uncomment this line.
#return '%s/pos_landmark.tfrecord' % (output_dir)	      #if you want to generate pos_landmark tfrecord,uncomment this line.
#return '%s/neg_landmark.tfrecord' % (output_dir)	      #if you want to generate neg_landmark tfrecord,uncomment this line.
return '%s/part_landmark.tfrecord' % (output_dir)	      #if you want to generate part_landmark tfrecord,uncomment this line.
这样即可
