### ISSUE TITLE
在python3上运行gen_landmark_aug_12.py文件出现‘map’ object is not subscriptable的错误，应该如何解决呢？

### ISSUE THREAD

**Issue by DaLei001** [AITTSMD/MTCNN-Tensorflow#151]
Traceback（most recent call last）:
File "gen_landmark_aug_12.py",line 189 in <module>
        ims,landmarks = GenerateData(train_txt, OUTPUT,net,argument = True)
File "gen_landmark_aug_12.py",line 61 in GenerateData
        data = getDataFromTxt(ftxt)
File "BBox_utils.py", line 71, in getDataFromTxt
        result.append(img_path,BBox(bbox),landmark)
File "BBox_utils.py", line 71, in __init__
        self.left = bbox[0]
TypeError:‘map’ object is not subscriptable

在python3在运行的gen_landmark_aug_12.py文件出现如上错误，应该怎么解决呢？

**Comment by littlesquirrel2017** [comment]
同样出现此问题，求助

**Comment by littlesquirrel2017** [comment]
耶✌，我把这个问题解决啦，在BBox_utils.py的113行把 bbox = map(int,bbox) 换为bbox = [int(_) for _ in bbox]，就ok啦

**Comment by zm931116** [comment]
把map强制转化为list类型就可以了
