### ISSUE TITLE
关于gen_12net_data.py中gt de offset的疑问

### ISSUE THREAD

**Issue by songyy137222** [AITTSMD/MTCNN-Tensorflow#152]
offset_x1 = (x1 - nx1) / float(size)
 offset_y1 = (y1 - ny1) / float(size)
 offset_x2 = (x2 - nx2) / float(size)
 offset_y2 = (y2 - ny2) / float(size)
其中offset_x1和offset_x2不应该除以gt的宽吗？
其中offset_y1和offset_y2不应该除以gt的高吗？
@AITTSMD 求大神解惑

**Comment by AITTSMD** [comment]
@songyy137222 测试的时候，gt不知道是多少啊
