### ISSUE TITLE
mtcnn的人脸检测和关键点检测为什么可以分别训练啊？？？

### ISSUE THREAD

**Issue by songyy137222** [AITTSMD/MTCNN-Tensorflow#153]
人脸检测和关键点检测同是训练一个网络，但是为什么可以分着训练，我明白是因为没有相关数据库，但我不懂的是这样训练出来的结果为什么还这么好？？？

**Comment by songyy137222** [comment]
@AITTSMD

**Comment by AITTSMD** [comment]
@songyy137222 补充一下多任务学习的知识

**Comment by NoahLu1105** [comment]
@songyy137222    所以，楼主知道是为啥了不？ 求深刻教育
