### ISSUE TITLE
为什么测试自己的视频时，视频会被放慢

### ISSUE THREAD

**Issue by victoriachen08** [AITTSMD/MTCNN-Tensorflow#154]
已经训练好模型，在测试自己的视频时，视频会被放慢很多。为什么？怎么样才能让视频变得正常

**Comment by victoriachen08** [comment]
@AITTSMD

**Comment by qinhui99** [comment]
会不会是自己的视频尺寸比较大？ 尺寸越大，检测的时间应该就越长。

**Comment by victoriachen08** [comment]
感谢你的回答 @qinhui99 我在camera_test.py中的video_capture.set(3, 340)，video_capture.set(4, 480) 改成了（3,1920) 和(4,1080)但是测试video的时候播放还是很慢

**Comment by choice17** [comment]
@victoriachen08 the resolution of your camera input setup is too big for real time, put it from
<pre>
video_capture.set(3, 1920), video_capture.set(4, 1080) </pre>
back to 
<pre> video_capture.set(3, 640), video_capture.set(4, 360) </pre>
