### ISSUE TITLE
gen_rnet_tfrecords.py

### ISSUE THREAD

**Issue by WJSAI** [AITTSMD/MTCNN-Tensorflow#155]
运行gen_rnet_tfrecords.py文件后产生错误gchengSegmentation fault (core dumped)该怎么解决@AITTSMD

**Comment by sumsuddin** [comment]
Maybe [this one ](https://github.com/AITTSMD/MTCNN-Tensorflow/pull/163)will help you. 
Remove `tfrecord_writer.close()` at [66th line](https://github.com/AITTSMD/MTCNN-Tensorflow/blob/b8631ba56ef5f3230f4c41358ef6dfcb94d114b9/prepare_data/gen_RNet_tfrecords.py#L66).

**Comment by sumsuddin** [comment]
Great!! Hopefully, @AITTSMD will merge [this](https://github.com/AITTSMD/MTCNN-Tensorflow/pull/163) pull request so that the issue will be fixed.
