### ISSUE TITLE
模型训练完之后测试检测不出人脸

### ISSUE THREAD

**Issue by songyy137222** [AITTSMD/MTCNN-Tensorflow#157]
你好，我训练的p、r、o、三个模型训练时显示的acc分别是0.94,0.98,0.98，但我用one_image_test.py测试时，根本检测不出人脸，我把三个阈值调到0.5以下，会有很多错误的人脸框，请问这是我训练的不正确吗，但我是按作者的步骤一步步来的啊

**Comment by NoahLu1105** [comment]
@songyy137222  请问你的解决了么？
