### ISSUE TITLE
image_size is not set properly for PNet test_mode in gen_hard_example.py

### ISSUE THREAD

**Issue by sumsuddin** [AITTSMD/MTCNN-Tensorflow#160]
In [this script](https://github.com/AITTSMD/MTCNN-Tensorflow/blob/b8631ba56ef5f3230f4c41358ef6dfcb94d114b9/prepare_data/gen_hard_example.py#L215) When I pass `PNet` as `test_mode` like this,

`$ python gen_hard_example.py --test_mode PNet`

The image_size variable is not set to `24`. No matter what param I pass as `test_mode` the `image_size` is always 48. So it is not generating input images for training `RNet`.

Please have a look or correct me if I am wrong somewhere. TIA

**Comment by liuyunwww** [comment]
https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_hard_example.py
Line 215
Change ONet to RNet

**Comment by sumsuddin** [comment]
Thanks, @liuyunwww !! Yes, I did the same to make it work. Here is a [pull request](https://github.com/AITTSMD/MTCNN-Tensorflow/pull/164) where I tried to fix the issue and set the image size accordingly to the flag. Can you have a look and suggest me to improve?
