### ISSUE TITLE
训练RNet后，运行one_image_test.py时bbox框出界。

### ISSUE THREAD

**Issue by liuyunwww** [AITTSMD/MTCNN-Tensorflow#162]
Instructions for updating:
Use the retry module or similar alternatives.
(1, ?, ?, 3)
(1, ?, ?, 10)
(1, ?, ?, 10)
(1, ?, ?, 16)
(1, ?, ?, 32)
(1, ?, ?, 2)
(1, ?, ?, 4)
(1, ?, ?, 10)
./data/MTCNN_model/PNet_landmark
(256, 24, 24, 3)
(256, 22, 22, 28)
(256, 11, 11, 28)
(256, 9, 9, 48)
(256, 4, 4, 48)
(256, 3, 3, 64)
(256, 576)
(256, 128)
(256, 2)
(256, 4)
(256, 10)
0 images done
[0.00011708]
[ 2.93596156e+01 -6.52301640e+00  4.66642327e+02  4.61017590e+02
  1.17080446e-04]

改了这两个参数
thresh从[0.6, 0.6, 0.7]改成[0.4, 0.05, 0.7]
epoch从[18, 14, 22]改成[30, 22, 22]

没有landmarks数据

**Comment by liuyunwww** [comment]
左下角的坐标在界内。

**Comment by liuyunwww** [comment]
边框的左下角的坐标在照片内。

**Comment by AITTSMD** [comment]
@liuyunwww 你的问题是？

**Comment by liuyunwww** [comment]
我运行one_image_test.py测试RNet模型的是否能检测出狗脸，结果bbox框右上角超出图片的范围。
我想请问，如何才能解决这个问题？

**Comment by liuyunwww** [comment]
@AITTSMD

**Comment by AITTSMD** [comment]
[max(0,left_x),  max(0,left_y), min(width,rightx), min(height,righty)]

**Comment by liuyunwww** [comment]
谢谢！
为什么会出现负值？

**Comment by liuyunwww** [comment]
谢谢！
 为什么bbox的坐标值会出现负值？
