### ISSUE TITLE
Dimension Error In MTCNN_Model

### ISSUE THREAD

**Issue by Aswiniloukya** [AITTSMD/MTCNN-Tensorflow#17]
When i am training in p-net Layer using the script train_Pnet.py.I got an error in the script of Mtcnn_model.py at 
line no: 144 
cls_prob = tf.squeeze(conv4_1,[1,2],name='cls_prob')

The error is ValueError: Can not squeeze dim[1], expected a dimension of 1, got 19 for 'cls_prob' (op: 'Squeeze') with input shapes: [384,19,19,2].   
Can anyone explain what this error meant for.

**Comment by ilyanelken** [comment]
@Aswiniloukya Hi, it seems like the input training data you are using for PNET is not 12x12 as it should be. Each training sample should be 3 channel 12x12 image.

**Comment by AITTSMD** [comment]
@Aswiniloukya Check the input dimension.

**Comment by Aswiniloukya** [comment]
Thank-you for your Response.
