### ISSUE TITLE
camera_test.py

### ISSUE THREAD

**Issue by victoriachen08** [AITTSMD/MTCNN-Tensorflow#172]
我运行了camera_test.py,除了显示每个网络所用时间外，还会显示人脸的个数，格式是（1，10）。但是无论前面1变成多少。后面的10 都保持不变。所以我想不要显示那个10（因为不知道它的作用是什么）。想知道写这句的代码在哪里？？？？

**Comment by victoriachen08** [comment]
@AITTSMD

**Comment by AITTSMD** [comment]
ctrl+f print
