### ISSUE TITLE
Pnet中的pooling的尺寸？

### ISSUE THREAD

**Issue by zaidao2023** [AITTSMD/MTCNN-Tensorflow#178]
代码中Pnet pooling的尺寸是2*2? 和论文中有区别 是否有别的用意？

**Comment by zaidao2023** [comment]
def P_Net(inputs,label=None,bbox_target=None,landmark_target=None,training=True):
    #define common param
    with slim.arg_scope([slim.conv2d],
                        activation_fn=prelu,
                        weights_initializer=slim.xavier_initializer(),
                        biases_initializer=tf.zeros_initializer(),
                        weights_regularizer=slim.l2_regularizer(0.0005), 
                        padding='valid'):
        print inputs.get_shape()
        net = slim.conv2d(inputs, 10, 3, stride=1,scope='conv1')
        print net.get_shape()
        net = slim.max_pool2d(net, kernel_size=[2,2], stride=2, scope='pool1', padding='SAME')
        print net.get_shape()

部分代码如上？

**Comment by AITTSMD** [comment]
@zaidao2023 Nothing special，thank u~
