### ISSUE TITLE
关于模型测试是的问题

### ISSUE THREAD

**Issue by Rogerluojie** [AITTSMD/MTCNN-Tensorflow#19]
你好，我在对于训练好的模型测试时发现，正脸时5个关键点都很好地拟合对应位置，但是将图片倾斜（相当于正脸旋转了一定的角度）一定的角度测试时，5个关键点的位置就会偏差很大，所以我想问出现这种情况可能会是哪些问题引起的呢？在图像预处理的时候是否需要做正脸旋转处理呢？
谢谢！

**Comment by AITTSMD** [comment]
@Rogerluojie 您好，我在特征点训练的过程中对数据集做了随机旋转、镜像等数据增强操作，但我旋转的角度仅为5度左右。建议您在训练前增大旋转角度，或者旋转随机角度。

**Comment by Rogerluojie** [comment]
@AITTSM 谢谢！！！我已经对图像集做了翻转和分别旋转10度、20度、30度的处理，训练得到的模型效果偏差很大，有没有可能会是所有数据放一起训练时原始图像的数据集比旋转翻转处理后的数据集小很多的情况引起的呢？

**Comment by AITTSMD** [comment]
@Rogerluojie 你好，旋转以后的坐标位置是否计算正确，可以可视化出来看看。我感觉不是数据量差别大引起来的，因为我们对所有的特征点检测部分的数据shuffle后再取batch的。

**Comment by dl8207531** [comment]
@AITTSMD 看你生成关键点样本里只旋转5度，感觉5度偏小，这个是有什么原因吗？容易收敛？
