### ISSUE TITLE
train.py 函数中的 random_flip_images

### ISSUE THREAD

**Issue by SunshineJZJ** [AITTSMD/MTCNN-Tensorflow#205]
@AITTSMD 请问这个函数的作用是什么，数据增强吗？我现在用95点数据训练，然后修改这部分代码有点麻烦，所以直接把这部分代码注释掉了，请问这样做对后续影响不大吧？

**Comment by AITTSMD** [comment]
@SunshineJZJ 对，就是为了做数据增强
