### ISSUE TITLE
MTCNN增点训练

### ISSUE THREAD

**Issue by SunshineJZJ** [AITTSMD/MTCNN-Tensorflow#206]
@AITTSMD 现在用MTCNN训练了95点数据，关键点的贴合度不是很精确，请问有没有办法提高一下啊？

**Comment by actionLUO** [comment]
@SunshineJZJ 感觉你可以试试其他的损失函数，比如wing loss！具体的训练结果还需要你自己去验证

**Comment by AITTSMD** [comment]
@SunshineJZJ MTCNN本身还是直接使用神经网络回归特征点的位置，这样效果不会很好，可以试试最近基于heatmap的方法

**Comment by SunshineJZJ** [comment]
谢谢@AITTSMD
谢谢@actionLUO

**Comment by zhoupan9109** [comment]
您好，我也在做增点训练，请问训练代码需要修改吗？具体修改哪些部分呢？请指点一下。@SunshineJZJ @actionLUO

**Comment by Happythinker** [comment]
@SunshineJZJ  
@actionLUO 
您好，我最近也在做增点训练，请问训练代码需要修改吗？具体要修改哪一部分呢？谢谢

**Comment by JACKYLUO1991** [comment]
@Happythinker 涉及landmark操作的部分，包括源数据的预处理和提取部分都要修改(face++和商汤的都可以用，不过可能要收费)，具体操作的话，建议详细阅读一下作者@AITTSMD的源码，你就会慢慢明白的，不过我本人将点扩增到106个后，效果不是很好...存在某些点的漂移过大，目前还在优化中...

**Comment by Happythinker** [comment]
@actionLUO ,请问您一下，对ONet的训练，源数据中的landmark超出人脸框可以吗，还是严格要求点坐标都必须在人脸框里？

**Comment by huangxiaojun1996** [comment]
@SunshineJZJ 你好，我最近在使用MTCNN进行增点训练，训练68点的关键点，使用的数据集是ibug_300W_large_face_landmark_dataset，我仅修改ONet中的output，但是这样的方式使得我训练时损失一直在0.06左右波动。按照作者@AITTSMD的源码训练损失可以下降到0.003左右。请问您是如何修改ONet的网络？
