### ISSUE TITLE
error occurred when i run gen_hard_example.py

### ISSUE THREAD

**Issue by hqq1990** [AITTSMD/MTCNN-Tensorflow#211]
when i run gen_hard_example.py, there is an issue occurred shown as below:
![2018-10-29 2 48 12](https://user-images.githubusercontent.com/26375756/47631506-b0eb1900-db89-11e8-8a97-abb460253de6.png)

anyone who can help me solve it, thank you.

**Comment by chochaashish** [comment]
Hi, @hqq1990
I'm facing the same issue, please help me if you have resolved "the params dictionary is not valid" issue.
thank you.

**Comment by wanggoudanscd** [comment]
@chochaashish 
Hi,I'm also facing the same issue, please help me if you have resolved "the params dictionary is not valid" issue.
thank you.
