### ISSUE TITLE
没有测试结果，怎么计算test  acc

### ISSUE THREAD

**Issue by kingsley851102** [AITTSMD/MTCNN-Tensorflow#219]
hi：
   我使用你的工程代码进行MTCNN学习，并复现训练过程，但是发现工程中没有关于测试的验证，请问你是怎么计算test acc的？我怎么验证我train 出来的模型没有过拟合或欠拟合？谢谢

**Comment by hqq1990** [comment]
你好，能不能和你交流一下复现的过程，我遇到点问题不会解决

**Comment by zm931116** [comment]
对于目标检测问题一般只是衡量precision和recall,你可以用相关代码生成测试结果然后在WIDER FACE官网下载评估程序绘制P-R曲线

**Comment by m29110938** [comment]
请问你们有成功执行train_PNet.py吗
