### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by caomaozjh** [AITTSMD/MTCNN-Tensorflow#228]
各位大神，我直接使用提供的模式做的测试，感觉结果不正确，连耳朵的置信度得分都能到1.0，请问是模型问题，还是其他原因呢？

**Comment by onzone** [comment]
Hey, did you solve the issue? I am trying this repo to train my own face detection mtcnn model and I am in middle of training RNet. If it's not giving anything close to to the paper, then I won't waste any time further.
