### ISSUE TITLE
wider_face_train.txt和官网给出的wider_face_train_bbx_gt.txt不一样

### ISSUE THREAD

**Issue by ChuanyangZheng** [AITTSMD/MTCNN-Tensorflow#229]
你好，WIDER官网下载的数据集当中只有wider_face_train_bbx_gt.txt，而且标注是整型，你的文件夹里包含了wider_face_train.txt文件，却是浮点型，精度会高一些，你是怎么得到wider_face_train.txt文件的，谢谢

**Comment by chenweilong915** [comment]
在prepare/data_util.py里面有相关的处理的~

**Comment by ChuanyangZheng** [comment]
我在里面找到了，谢谢啦
