### ISSUE TITLE
gen_PNet_tfrecords.py

### ISSUE THREAD

**Issue by wanggoudanscd** [AITTSMD/MTCNN-Tensorflow#243]
@AITTSMD  您好~
我在执行gen_PNet_tfrecords.py时，出现File "E:/MTCNN-Tensorflow-master\prepare_data\tfrecord_utils.py", line 183, in _process_image_withoutcoder
    image_data = image.tostring()

AttributeError: 'NoneType' object has no attribute 'tostring'
这个问题，请问是怎么回事？
谢谢

**Comment by AITTSMD** [comment]
@wanggoudanscd 检查图像路径，图像路径有误

**Comment by wanggoudanscd** [comment]
您好,通过执行前几步我将negative、part、positive和train_PNet_landmark_aug放在了E:\MTCNN-Tensorflow-master\prepare_data\12该文件夹下，在执行gen_PNet_tfrecords.py时我的两个路径分别是：
dir = 'E:/MTCNN-Tensorflow-master/prepare_data/'
output_directory = 'E:/MTCNN-Tensorflow-master/prepare_data/imglists/PNet'
我试着改了路径，但一直是这个问题，想请教您一下。谢谢~
学生菜鸟一只，请您见谅！

在 2019-02-22 13:40:54，"陈少萌萌哒" <notifications@github.com> 写道：


@wanggoudanscd 检查图像路径，图像路径有误

**Comment by missyangyangyang** [comment]
你好，我也遇到了这个问题  image_data = image.tostring()
AttributeError: 'NoneType' object has no attribute 'tostring'我用的是Windows系统，路径的问题也还没解决。能问一下该怎么解决么

**Comment by kyawthiha31** [comment]
@missyangyangyang  I also have that error when I run for tf_record file.
Do you know the error is?
Does anyone know in this forum?

Traceback (most recent call last):
  File "gen_PNet_tfrecords.py", line 131, in <module>
    run(dir, net, output_directory, shuffling=True)
  File "gen_PNet_tfrecords.py", line 66, in run
    _add_to_tfrecord(filename, image_example, tfrecord_writer)
  File "gen_PNet_tfrecords.py", line 25, in _add_to_tfrecord
    image_data, height, width = _process_image_withoutcoder(filename)
  File "F:\mtcnn\MTCNN-Tensorflow-master\prepare_data\tfrecord_utils.py", line 183, in _process_image_withoutcoder
    image_data = image.tostring()
AttributeError: 'NoneType' object has no attribute 'tostring'
