### ISSUE TITLE
Get error:Key conv4_1/biases not found in checkpoint   when  i run python gen_hard_example for ONet

### ISSUE THREAD

**Issue by dyrusYan** [AITTSMD/MTCNN-Tensorflow#258]
Key conv4_1/biases not found in checkpoint
	 [[node save/RestoreV2 (defined at ../Detection/fcn_detector.py:29) ]]
	 [[node save/RestoreV2 (defined at ../Detection/fcn_detector.py:29) ]]
please help me

**Comment by rowheel** [comment]
Got the same issue here. However on line 202, file mtcnn_model.py I do find a disabled statement constructing a different conv4_1. However by replacing that with the original one does not help at all.

**Comment by dyrusYan** [comment]
> Got the same issue here. However on line 202, file mtcnn_model.py I do find a disabled statement constructing a different conv4_1. However by replacing that with the original one does not help at all.

I solved it. Problem occurred when we do not use the default prefix args['...','...','...' ]. Maybe the prefix arg you used was only ‘../RNet’, just like me,and It can not find the pnet model.
