### ISSUE TITLE
how to improve the accuracy of a model and confidence score

### ISSUE THREAD

**Issue by Sumanth214** [AITTSMD/MTCNN-Tensorflow#27]
Hi,
I am doing face detection using tensorflow. successfully I  got the face detection and found the number of detected faces. In the detection module some of the faces have not detected.
How can I resolve that and How do I want to improve the model accuracy or confidence score.

I am thinking, if I can change the hyper parameters i.e learning rate to improve the model accuracy
or again I need to train from starting onwards by changing the hyper parameters.
Can I train this model on another dataset. is this going to increase the model accuracy ?

thanks in advance

**Comment by AITTSMD** [comment]
@Sumanth214 hi,In my opinion，It's data that matters.So you can change the sample methods to get more  positive training data. For example,you can change the smallest size of face in **gen_12net_data.py#L85**  and change the number of iterations in **gen_12net_data.py#L109** .
    The original author used 800w training data to train MTCNN, while I used 100w. And you can also change batchsize and make it larger.

**Comment by ilyanelken** [comment]
@AITTSMD what do you mean by 100w and 800w?

**Comment by AITTSMD** [comment]
@ilyanelken Sorry for the late reply.The original author used 800w+ training data including pos,neg,part and landmark training data.In my project,I used  100w+(almost 200w) training data.

**Comment by ilyanelken** [comment]
@AITTSMD I am just asking about "800w+" notation, what does it mean? 800,000+ training samples?

**Comment by AITTSMD** [comment]
yes

**Comment by rashmisgh** [comment]
@AITTSMD I tried to make changes as you told to increase the accuracy but I got this issue how to resolve that.
The Issue is:- Traceback (most recent call last):
  File "gen_12net_data.py", line 114, in <module>
    delta_x = npr.randint(-w * 0.2, w * 0.2)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high

**Comment by oliviawindsir** [comment]
> @AITTSMD I tried to make changes as you told to increase the accuracy but I got this issue how to resolve that.
> The Issue is:- Traceback (most recent call last):
> File "gen_12net_data.py", line 114, in
> delta_x = npr.randint(-w * 0.2, w * 0.2)
> File "mtrand.pyx", line 993, in mtrand.RandomState.randint
> ValueError: low >= high

Try to check the value of your 'w'. The error is saying that your minimum range is larger than the  max range (syntax : npr.randint(minrange, maxrange)) Most probably due to your 'w' being a negative value.
