### ISSUE TITLE
train_pnet.py遇到报错

### ISSUE THREAD

**Issue by Mi-zo-re** [AITTSMD/MTCNN-Tensorflow#270]
在运行pnet训练脚本的时候在train.py里面报了如下错误，请问该怎么解决啊
tensorflow.python.framework.errors_impl. InvalidArgumentError: Feature:  image/landmark (data type: float) is required but could not be found.

**Comment by AITTSMD** [comment]
@Mi-zo-re 你是不是没有准备特征点的数据啊

**Comment by Mi-zo-re** [comment]
> @Mi-zo-re 你是不是没有准备特征点的数据啊
您是说landmark的那个代码吗，我执行了代码，包括后面把两个数据集整合到一起和record的工作我都做了

**Comment by Mi-zo-re** [comment]
> @Mi-zo-re 你是不是没有准备特征点的数据啊
我的问题解决了，可能是我当时做数据集封装的时候出了什么问题我没有弄明白，而且代码也不是您目前最新的版本，不过我今天用您最新的版本重新制作了训练集以后PNet可以正常运行了，所以说应该就是我数据集没有弄好，感谢作者的帮助
