### ISSUE TITLE
Did you do pyramid in testing?

### ISSUE THREAD

**Issue by kevinchang50105** [AITTSMD/MTCNN-Tensorflow#28]
Hi, 
Thanks for sharing the code.
Did you do resize the image to different scales to build an image pyramid just like paper did?
If yes, which .py is it?

Many thanks!

**Comment by ilyanelken** [comment]
@kevinchang50105 Hi, I think this is what you are looking for:
https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/Detection/MtcnnDetector.py#L198

**Comment by kevinchang50105** [comment]
@ilyanelken Thanks a lot!

**Comment by kevinchang50105** [comment]
@ilyanelken Can you explain why we need to use the scale like this first "current_scale = float(net_size) / self.min_face_size"? Thanks in advance.
