### ISSUE TITLE
gen_hard_example速度慢

### ISSUE THREAD

**Issue by kli017** [AITTSMD/MTCNN-Tensorflow#286]
你好，在gen_hard_example在运行时速度太慢，每张图要1-2秒。
在。gen_hard_example.py 参数gpu被注释掉了，请问是默认用的cpu吗

**Comment by Racha1992** [comment]
我的更甚，一张图要4-5秒。图太大，生成巨量的框，nms太慢了

**Comment by SURABHI-GUPTA** [comment]
I am getting ckpt model dict as None while running this file

**Comment by JianyuanYin** [comment]
> I am getting ckpt model dict as None while running this file

Does that work?How to set it? Many Thanks
