### ISSUE TITLE
Pyramid scaling

### ISSUE THREAD

**Issue by kevinchang50105** [AITTSMD/MTCNN-Tensorflow#29]
Hi @AITTSMD , can you explain why you use the scale like this first "current_scale = float(net_size) / self.min_face_size"? and then scale by 0.79. Thanks in advance.

**Comment by AITTSMD** [comment]
@kevinchang50105 hi,
1  we don't know the position and the scale of faces in the image,so we should construct pyramid to capture all faces.
2 net_size means the smallest  window for classification and min_face_size means the smallest size of face we want to detect.So we should rescale the image to let min_face_size equals net_size.
3 0.79 means scale factor.We use it to construct pyramid.You can change it.

**Comment by kevinchang50105** [comment]
Hi @AITTSMD , btw, did you use roi pooling in your code?

**Comment by AITTSMD** [comment]
No,I didn't use~
