### ISSUE TITLE
MTCNN Frozen Model

### ISSUE THREAD

**Issue by darktraxes** [AITTSMD/MTCNN-Tensorflow#31]
Hey guys,

I was wondering if there is a way to freeze the trained MTCNN model from this implementation into a protobuf file 

I've seen Facenet and also other examples requiring only one .pb frozen file that contain PNet,Rnet and also Onet into the same file. Is there a way to freeze my trained networks into one file being able to access the networks like this?
('pnet/conv4-2/BiasAdd:0', 'pnet/prob1:0'), feed_dict={'pnet/input:0':img}
('rnet/conv5-2/conv5-2:0', 'rnet/prob1:0'), feed_dict={'rnet/input:0':img}
('onet/conv6-2/conv6-2:0', 'onet/conv6-3/conv6-3:0', 'onet/prob1:0')

Thanks a lot!

**Comment by ilyanelken** [comment]
@darktraxes Hi, An optional solution might be saving this trained MTCNN model as numpy files (separate file for each sub-network) and after that loading this files into facenet implementation and generating frozen model file with:
'''
        frozen_model_file = '/tmp/mtcnn.pb'
        output_graph_def = tf.graph_util.convert_variables_to_constants(
            sess,
            tf.get_default_graph().as_graph_def(),
            ['pnet/conv4-2/BiasAdd',
             'pnet/prob1',
             'rnet/conv5-2/conv5-2',
             'rnet/prob1',
             'onet/conv6-2/conv6-2',
             'onet/conv6-3/conv6-3',
             'onet/prob1']
        )
        with tf.gfile.GFile(frozen_model_file , "wb") as f:
            f.write(output_graph_def.SerializeToString())
'''

**Comment by flankechen** [comment]
@ilyanelken hi, could you share how to share how to save the names and weights to .npy file? Thanks!
