### ISSUE TITLE
How to Create Annotation file(.txt) for Additional Images

### ISSUE THREAD

**Issue by Sumanth214** [AITTSMD/MTCNN-Tensorflow#32]
Hi.

           I want to add some more images for the existing dataset (WIDERFACE) for that i need to create annotation file, can anyone say how to create annotation file (.txt) for that additional images.

Thanks in advance.

**Comment by AITTSMD** [comment]
@Sumanth214 You can make annotation file for new data in any form.You need to parse it correctly to make tfrecord.
