### ISSUE TITLE
step 7

### ISSUE THREAD

**Issue by Lucas-work** [AITTSMD/MTCNN-Tensorflow#35]
你好,我在根据您开源的代码学习mtcnn.有个问题想请教一下:
step7时,要运行gen_hard_example.py生成generate training data for RNet. 
第143为什么会在Detector中restore RNet模型(我是重新训练,并没有data这个文件.)

**Comment by ltrottier** [comment]
You can do:
```
python gen_hard_example.py --test_mode pnet
```
to get training data for rnet. You don't need a pretrained rnet to do that.

By default, test_mode = rnet to generate images for onet. In this case, you need a pretrained rnet.

**Comment by ltrottier** [comment]
This:
```
python gen_hard_example.py --test_mode rnet
```
generates hard negatives for Onet.

For t_net, I'm not sure.
