### ISSUE TITLE
gen_hard_example.py的询问

### ISSUE THREAD

**Issue by lihui52** [AITTSMD/MTCNN-Tensorflow#36]
首先感谢您的代码，我在实现的时候有些地方没看明白，还望您能指教下：
1. 您的代码中，有两处需要调用这个函数，在步骤7中，您给出的是python gen_hard_example.py --test_mode pnet,但是在t_net函数中，已经设定了test_mode 为PNet，有点不明白
2.在后面一次产生训练样本时，是否使用命令 python gen_hard_example.py --test_mode rnet? t_net函数需要改变吗？
再次感谢您

**Comment by AITTSMD** [comment]
@lihui52 您好，gen_hard_example.py主要是用来产生RNet和ONet的训练样本。产生RNet的训练样本时，test_model应设为PNet，当产生ONet的训练样本时，test_model应设为RNet。直接在parse_args函数中修改test_model的默认参数就可以了~

**Comment by lihui52** [comment]
@AITTSMD 了解了，多谢！
