### ISSUE TITLE
人脸的五个特征点检测不准确问题?

### ISSUE THREAD

**Issue by frotms** [AITTSMD/MTCNN-Tensorflow#38]
您好,
用这个模型作人脸检测和对齐时遇到一个问题: 人脸特征点的检测不太准. 
请问一下是这个模型本身就存在这个缺陷吗?

**Comment by AITTSMD** [comment]
@frotms 您好，论文中用celeba训练特征点检测的部分，效果挺好。我当时用其它数据集训练的特征点检测部分，您可以尝试用celeba重新训练。
