### ISSUE TITLE
class TestLoader:

### ISSUE THREAD

**Issue by bjmajic** [AITTSMD/MTCNN-Tensorflow#40]
def get_batch(self):
        imdb = self.imdb[self.cur]
        im = cv2.imread(imdb)
       self.data = im

您好，最近参考您的代码，请问TensorFlow处理的时候（使用tf.image.decode_jpeg）,颜色顺序是RGB， 但是opencv是BGR， 是不是应该用cv2.cvtColor(im, cv2.COLOR_BGR2RGB)转换一下

**Comment by AITTSMD** [comment]
@bjmajic 不需要喔，保证训练和测试的图像通道顺序一致即可。

**Comment by bjmajic** [comment]
@AITTSMD 了解。请问一下，您这个tfrecord制作的时候，是使用tf.gfile()的方式read的encoded数据，然后使用tf.image.decode_jpeg 解码， 这样得到的不是RGB的顺序么？我写了一个小程序，用红色的图像测试了一下，是RGB顺序。 又或者我没看仔细您的处理流程，您是把tf.image.decode_jpeg后的图像交换了颜色通道的顺序么
