### ISSUE TITLE
One question on generate_bbox for generating the bounding box from the heatmap produced by PNET 

### ISSUE THREAD

**Issue by mathqiong** [AITTSMD/MTCNN-Tensorflow#42]
Hi ya,

At test, given an image, the PNet outputs the heatmaps of classification scores (i.e. H*W*2) and the offsets 
(i.e. H*W*4) for each position. Then the python function generate_bbox is used to produce the bounding box for the image. I was confused how this generate_bbox works. What's the meaning of the offsets (i.e. H*W*4) for each position.

Many thanks

**Comment by AITTSMD** [comment]
@mathqiong hi,when we test an image, the PNet outputs the heatmaps of classification scores and the offsets each position. generate_bbox does the following things:
 1. find the positions where classification score > threshold.
 2. project the positions in 1 to the original image.
 3. keep the offsets(as for the ground truth) for the postions in 1
