### ISSUE TITLE
strange threshold for three net 0.4, 0.05, 0.7 

### ISSUE THREAD

**Issue by tpys** [AITTSMD/MTCNN-Tensorflow#45]
They are quite different from the other implementation such as 0.6 0.6 0.7 for pnet rnet and onet respectively, so what cause these threshold value different?

**Comment by AITTSMD** [comment]
@tpys In which code?

**Comment by tpys** [comment]
@AITTSMD in generate_hard_example.py function parse_args, after read your other issues, i understand lower the threshold to increase pos example, right?  from trained pnet i can get 14w+ pos example, but from trained rnet i can get 16w+ example, less than yours 19w+,  do I need low the threshold for rnet a little bit more or train rnet for more epoch?
