### ISSUE TITLE
训练其他关键点结果不准的问题

### ISSUE THREAD

**Issue by lihui52** [AITTSMD/MTCNN-Tensorflow#46]
您好，我想训练上下嘴唇的点，也进行标注了，但是发现两个点总是融合为一个点，我想请问下，是数据的问题还是模型的问题呢？麻烦您了

**Comment by AITTSMD** [comment]
@lihui52 首先您要检查原始的训练集标注的特征点是否准确，可视化出来看看。然后，在训练的过程中，如果做了镜像的话，注意特征点的位置要做相应的转化。

**Comment by flankechen** [comment]
watch out for the landmarks in data augment and random flip

**Comment by qiudi0127** [comment]
@AITTSMD 那如果训练上下嘴唇的中心点的话，训练过程中对这两个点的镜像是不是会影响这两个点的准确度，这两个点相当于与鼻尖那个点在一条线上。

**Comment by AITTSMD** [comment]
@qiudi0127 不好意思回复晚了，您的意思是要预测上下嘴唇的中心点，在做镜像时同样需要做相应的转换，而且这两个点和鼻尖的那个点也不一定在同一条线上。
