### ISSUE TITLE
why the  ContROC score so low than DiscROC

### ISSUE THREAD

**Issue by tpys** [AITTSMD/MTCNN-Tensorflow#47]
After finish training onet, I test trained model on FDDB with your code RunOnFDDBLandmark.py, I change the trained epoch from [18, 14, 16] to [30, 22, 22], keep threshold [0.6, 0.15, 0.05] same, then I got DiscROC 
![discroc](https://user-images.githubusercontent.com/3313406/34189959-22dcad4c-e579-11e7-86d3-8c195b58ee83.png)
ContROC
![controc](https://user-images.githubusercontent.com/3313406/34189984-39737676-e579-11e7-954a-286d0f3845ee.png)

My question:

 The DiscROC is similar with yours, but the ContRoc seems not good? so is there something wrong in the code, what can I do to improve this cure?

The threshold setting are really confused me, in one_image_test.py you set them to [0.9, 0.6, 0.7], but in RunOnFDDBLandmark.py you set them to [0.6, 0.15, 0.005], again in gen_hard_example.py you set them [0.4, 0.05, 0.7],  so how to setting these threshold in my application, are there some principle to follow.

Thanks for sharing this code, it helps me a lot!!!

**Comment by AITTSMD** [comment]
@tpys hi,In my opinion, the threshold varies with, the apllication.if u want the model to be faster,set pnet's theshold higher.if u want the model to be more accurate,set pnet's theshold lower.Actually,I don't know how to set these threshold correctly.Just test.

**Comment by tpys** [comment]
OK, got you, higher threshold lead to faster, lower threshold lead to more accurate, thank you. But how to improve the ContROC, do you have any clue?

**Comment by AITTSMD** [comment]
@tpys sorry，I don't.if u have any clue,please tell me~

**Comment by flankechen** [comment]
@tpys in my experience, it's quite normal for the contRoc curve to be lower than discRoc.
http://old.faceplusplus.com.cn/fddb/
http://vis-www.cs.umass.edu/fddb/fddb.pdf

**Comment by tpys** [comment]
@flankechen I see, many thanks.
