### ISSUE TITLE
The stocked model gives worse result?

### ISSUE THREAD

**Issue by serser** [AITTSMD/MTCNN-Tensorflow#49]
It seems the results are not as good as it is publicized. 

(打扰了，请问例子给出的结果用的是提供的模型吗？)

No face detected in this image:

![fb_indian_1204_100](https://user-images.githubusercontent.com/3620404/34353496-8315dece-ea63-11e7-8d92-25976cfa587f.jpg)

Some obvious faces are not detected in this image (also sensitive with occlusion/hat, rotation, blur, over-

![lala_screenshot_26 12 2017_16](https://user-images.githubusercontent.com/3620404/34353723-cb7e5fa0-ea64-11e7-93c5-fce179e9120e.png)
exposure):

![lala_screenshot_26 12 2017](https://user-images.githubusercontent.com/3620404/34353693-a5a6bf66-ea64-11e7-9c64-210506ac9744.png)

![lala_screenshot_26 12 2017_15](https://user-images.githubusercontent.com/3620404/34353703-b301db64-ea64-11e7-89d7-b776fad65d32.png)

![lala_screenshot_26 12 2017_13](https://user-images.githubusercontent.com/3620404/34353710-b8827602-ea64-11e7-8472-e6bd95b6f5d3.png)

![lala_screenshot_26 12 2017_5](https://user-images.githubusercontent.com/3620404/34353716-bd56900a-ea64-11e7-8f0d-7197a69a187e.png)

Plus, if provided more epochs of training, does the problem resolve?

**Comment by serser** [comment]
I’ve found several original images of demoed ones. And I run on v2 with stocked model, here are the results I get. There are indeed differences compared to the shown results.

![lala_screenshot_26 12 2017](https://user-images.githubusercontent.com/3620404/34354058-ad27a4ec-ea66-11e7-8c52-8a90acdfd460.png)
![lala_screenshot_26 12 2017_1](https://user-images.githubusercontent.com/3620404/34354059-ad5b3be0-ea66-11e7-9215-3ad39667aba4.png)
![lala_screenshot_26 12 2017_3](https://user-images.githubusercontent.com/3620404/34354060-ad8efb7e-ea66-11e7-9940-1234fe74e2a6.png)
![lala_screenshot_26 12 2017_4](https://user-images.githubusercontent.com/3620404/34354061-adbe8a10-ea66-11e7-8b04-8ced5a53cf4f.png)
![lala_screenshot_26 12 2017_5](https://user-images.githubusercontent.com/3620404/34354062-adeb5a22-ea66-11e7-802d-832ef34818a4.png)

**Comment by AITTSMD** [comment]
@serser hi,I used the model provided to get results.Have you tried the model offered by original author（https://github.com/kpzhang93/MTCNN_face_detection_alignment）.In my past experiment，I also found this model was sensitive with rotation.
As for my examples,It's important to  adjust 3 nets' thresholds.Keep them lower to have a try.

**Comment by serser** [comment]
Lowering thresold does help (after trying many times, I've set them to `[0.1, 0.1, 0.1]`), but it seems it does so at the cost of speed (`1 fps` on average). It is slower, and it sometimes introduces false detections as well. Turns out that it is not dramatically improve the performance when having been lowered to some level, say below `0.5`.

**Comment by AITTSMD** [comment]
@serser set pnet's threshold higher(0.6),rnet's threshold(0.15) and onet's threshold(0.05) lower.The model's speed mainly depends on pnet's threhold, as it produces proposals.By the way,to detect faces that rotate，It's important to do more affine transforms and train more epochs when training mdels.Hope it helps!
