### ISSUE TITLE
关于landmark的一些询问！

### ISSUE THREAD

**Issue by T-mac93** [AITTSMD/MTCNN-Tensorflow#5]
您好，看到您回答问题都是用的中文，所以我就用中文了。我最近也是在用tensorflow来复现mtcnn，基于的是之前的一个mxnet的上进行的修改，然后我的问题主要就是在landmark的问题上。我所用的landmark的数据就是从celebA中得到的，我所用的方式就是按照celebA给出的bbox信息，直接裁剪出bbox的图片，然后相对于gt的bbox得到landmark的几个坐标相对于gt的bbox的偏移量再除以size，然后直接把这个作为train的landmark的信息，和pos，neg，part的信息放进去进行train，但是loss还是不够满意，我看了下您的landmark的设置，觉得比我的要复杂很多，可否简单给我讲讲您这部分的思路呢？非常感谢

**Comment by AITTSMD** [comment]
@T-mac93 您好，celeba中有些数据是标注有误的，这里需要注意一下。我之前也是用celeba训练特征点的部分，可是发现loss有规律的波动。所以我用了现在的人脸特征点检测的数据，因为数据较少，所以使用了数据增强。对于一张gt，通过对其平移，旋转和随机镜像，增加样本。不过需要注意对应特征点坐标的转换。

**Comment by T-mac93** [comment]
@AITTSMD  谢谢您的解答。当然我的主要问题是，您觉得我标注我的landmark坐标的方式有没有问题？还有就是我想知道是您的关键点的坐标是如何标注的呢？

**Comment by AITTSMD** [comment]
@T-mac93 我的关键点的坐标计算方式：设bbox左上角的坐标为（x,y）,bbox的大小为w和h，左眼睛的坐标为（x1,y1）,计算坐标为（x1-x）/w，（y1-y）/h.其它部分的计算方式相同，主要是计算与bbox左上角坐标的offset。

**Comment by T-mac93** [comment]
@AITTSMD  nice！非常感谢，您的做法跟我是一样的，我运行了你的代码，可以训练，然后进行了测试，结果不错。最后一个问题，我想知道您最后的landmark的loss是多少呢？

**Comment by AITTSMD** [comment]
@T-mac93 具体多少忘了，看曲线是收敛了。

**Comment by houzidexiaoloulou** [comment]
@AITTSMD 您好，非常感谢开源的代码，我在使用代码训练自己的数据时landmark loss一直不收敛，有时会出现nan的情况，其他loss正常，我的训练图片大概是800*600大小，200张，请问有什么好的建议吗？

**Comment by AITTSMD** [comment]
@houzidexiaoloulou 您好，建议您：
1 将特征点的位置可视化出来，看看特征点标注的位置是否正确。
2 检测特征点检测部分的标签是绝对坐标还是相对坐标。

**Comment by houzidexiaoloulou** [comment]
@AITTSMD 您好
1、特征点是准确的，是绝对坐标送入gen_12net_data.py中，现增加数据集至2200张，landmark loss在0.5~0.6之间跳动，其他loss正常。
2、在代码中观察到您的3个损失是一起更新的 （  train_op, lr_op = train_model(base_lr, radio_cls_loss*cls_loss_op + radio_bbox_loss*bbox_loss_op + radio_landmark_loss*landmark_loss_op + L2_loss_op, num)  ）请问这样会有影响吗？

**Comment by houzidexiaoloulou** [comment]
@AITTSMD 您好
1、特征点是准确的，是绝对坐标送入gen_12net_data.py中，现增加数据集至2200张，landmark loss在0.5~0.8之间跳动，其他loss正常。
2、在代码中观察到您的3个损失是一起更新的 （ train_op, lr_op = train_model(base_lr, radio_cls_losscls_loss_op + radio_bbox_lossbbox_loss_op + radio_landmark_loss*landmark_loss_op + L2_loss_op, num) ）请问这样会有影响吗？

**Comment by houzidexiaoloulou** [comment]
@AITTSMD 您好
1、特征点是准确的，是绝对坐标送入gen_12net_data.py中，现增加数据集至2200张，landmark loss在0.5~0.8之间跳动，其他loss正常。
2、在代码中观察到您的3个损失是一起更新的 （ train_op, lr_op = train_model(base_lr, radio_cls_losscls_loss_op + radio_bbox_lossbbox_loss_op + radio_landmark_loss*landmark_loss_op + L2_loss_op, num) ）请问这样会有影响吗？

**Comment by AITTSMD** [comment]
@houzidexiaoloulou 不好意思，回复晚了。因为mtcnn是multi-task的网络，所以我按不同的权重将三个任务的loss加起来，进行反向传播。

**Comment by houzidexiaoloulou** [comment]
@AITTSMD 谢谢你的回答。我调整图片和参数之后landmark loss在0.1~0.3之间波动请问这属于正常情况吗，或则请问有什么修改的意见吗？

**Comment by qiudi0127** [comment]
@AITTSMD 您好，我想问一下您是如何设置三个任务loss的权重，比例是多少？

**Comment by shiyuanyin** [comment]
@AITTSMD 
您好，请问，这个版本的ｍｔｃｎｎ能够训练１３个的关键点，并和５个关键点位置的精度差不多，增点训练，需要注意什么吗，还是说增点训练最好不用这个模型了，因为我增点不多，多增加了８个点，请问您有好的解决方法吗？

**Comment by Happythinker** [comment]
@shiyuanyin 请问您增点修改的地方多么，我用的这个版本的mtcnn修改的增点到68，关键点的位置偏差挺大，可以交流一下吗？
