### ISSUE TITLE
NotFoundError (see above for traceback): Key fc1/alphas not found in checkpoint

### ISSUE THREAD

**Issue by MetaPeak** [AITTSMD/MTCNN-Tensorflow#51]
Hi, When I run the code in your test directory, it comes out this error 
`NotFoundError (see above for traceback): Key fc1/alphas not found in checkpoint`
I wonder is there some thing changed in the defined Graph of the R-Net and O-Net?

**Comment by ilyanelken** [comment]
@MetaPeak Hi, please see:
https://github.com/AITTSMD/MTCNN-Tensorflow/issues/30
