### ISSUE TITLE
卷基层缺少bias

### ISSUE THREAD

**Issue by guangdongliang** [AITTSMD/MTCNN-Tensorflow#53]
@AITTSMD 您好！
         非常感谢您对MTCNN的复现。请问为什么P_net,R_net,O_net中的卷积层都未加bias呢，我看facenet的mtcnn模型中是有bias的。
         非常期待您的答疑解惑，谢谢您！

**Comment by AITTSMD** [comment]
@guangdongliang 不好意思，回复晚了。卷积层的bias在训练的过程中，没那么重要，所以我没有加。
