### ISSUE TITLE
PR 曲线是怎么画的

### ISSUE THREAD

**Issue by tzhang2014** [AITTSMD/MTCNN-Tensorflow#55]
@AITTSMD 感谢博主提供的训练代码，按照您的readme实现的结果在FDB上有93.2的准确率，但是我不知道怎么去画每个网络的PR曲线，博主能否指点下，多谢了

**Comment by AITTSMD** [comment]
@tzhang2014 你是要画召回率-准确率曲线吗？我觉得可以这样做：
1 统计fddb中gt的总数
2 统计mtcnn检测的结果，比如检测的框与任意gt的iou超过0.5就算正确。计算准确率和召回率。
3 调整3个网络的阈值，重复2过程，得一系列的准确率和召回率。就可以绘制对应的曲线了。

**Comment by tzhang2014** [comment]
@AITTSMD 哦哦，好。我先试下，多谢指教

**Comment by huangbo1221** [comment]
@tzhang2014 @AITTSMD  你们好，请问跑了FDDB的官方计算代码，得出了离散的和连续的PR曲线图，但是怎么看准确率是多少呢？tzhang2014说达到了93.2%的准确率，是怎么看出来的呢？
