### ISSUE TITLE
Understanding of PNet

### ISSUE THREAD

**Issue by justyine** [AITTSMD/MTCNN-Tensorflow#56]
Hi, I have some confusion about PNet and is wondering if I understand the network correctly. From what I understood, PNet generates bounding box regressions from the heatmap in conv 3 and face classification will find the probability that a face is contained in the box. After that, generate_bbox finds the bounding boxes with classification score higher than the threshold and project the locations back to the original image. Is that correct?
I'm also wondering why conv 4-1 and conv 4-2 are 1x1x2 and 1x1x4 feature maps instead of fully connected layer?
Thank you.

**Comment by AITTSMD** [comment]
@justyine Hi
1 correct
2 As you know,PNet is used to generate bboxes in images of arbitrary sizes.So,PNet should be fully convolutional network.

**Comment by justyine** [comment]
Thank you @AITTSMD !
