### ISSUE TITLE
关于训练loss

### ISSUE THREAD

**Issue by bjmajic** [AITTSMD/MTCNN-Tensorflow#57]
您好，我参考了您的mtcnn代码，打算用来检测人（不是人脸），发现回归的loss基本不变，请指点一下。我的回归目标是（x1, y1, x2, y2）这些值分别用（x2-x1, y2-y1）进行了归一化，数量级是0.02， 0,12这样。为了防止回归量太小，对回归量乘以10，
训练的时候，发现回归loss一直是0.4， 0.5， 一直降不下去。
除此之外，分类的loss，开始会降一点，后面几乎也不降了，最终的loss处于0.0x的状态

**Comment by bjmajic** [comment]
@AITTSMD gt 已经可视化了，是正确的。回归目标是左上角坐标（x1, y1） 和右下角目标（x2, y2）. 设计的时候是这样的。假设我正样本的坐标是(nx1, ny1, nx2, ny2), 对应的宽度和高度是w, h， 那么归一化后是 （x1-nx1）/w , （y1-ny1）/h,  （x2-nx2）/w , （y2-ny2）/h,   
分类的准确率是97%-98%
模型应该是没有问题，结构和人脸的基本一致，卷积和池化

**Comment by bjmajic** [comment]
@AITTSMD  这是我的卷积设置
 with slim.arg_scope([slim.conv2d], activation_fn=PRelu, weights_initializer=slim.xavier_initializer(),
                        biases_initializer=tf.zeros_initializer(),
                        weights_regularizer=slim.l2_regularizer(L2_REGULARIZER_VALUE),
                        padding='valid'):

**Comment by AITTSMD** [comment]
@bjmajic 不好意思，回复晚了。现在情况怎么样?这里的回归loss值得是pnet吗

**Comment by bjmajic** [comment]
@AITTSMD 是的，是pnet的loss，我现在还没开始训练r-net, 担心p-net效果不好的话，会影响r-net

**Comment by AITTSMD** [comment]
@bjmajic 测一下pnet的召回率。

**Comment by AITTSMD** [comment]
@bjmajic 测一下pnet的召回率。

**Comment by bjmajic** [comment]
@AITTSMD 好的，我试一下。多谢指导
