### ISSUE TITLE
关于样本比例问题

### ISSUE THREAD

**Issue by tzhang2014** [AITTSMD/MTCNN-Tensorflow#58]
博主您好，看了gen_imglist的时候，发现只有PNet那个做了1:1:3的，RNet和ONet直接用的hardsample生成的，但是我看里面的比例不是1：1：3,对训练结果是否会有大的影响？

**Comment by AITTSMD** [comment]
@tzhang2014 看一下README中的**Some Details**

**Comment by NoahLu1105** [comment]
@tzhang2014   请问，rnet和onet的样本比例该为多少呢？
