### ISSUE TITLE
compute iou error

### ISSUE THREAD

**Issue by kevin198528** [AITTSMD/MTCNN-Tensorflow#59]
in prepare_data/utils.py the function IoU
when i use [0,0, 2, 2] [[1, 1, 3, 3]] test  the result is 0.28 but acc is 0.14 
1/(4 + 4 -1) = 0.14
may be the source : 
box_area = (box[2] - box[0] + 1) * (box[3] - box[1] + 1)
should be 
box_area = (box[2] - box[0] ) * (box[3] - box[1])
thanks ,  i learned a lots from the project. best wishes

**Comment by AITTSMD** [comment]
@kevin198528 thanks
