### ISSUE TITLE
Issues about run this script four times to generate tfrecords of neg,pos,part and landmark respectively)

### ISSUE THREAD

**Issue by lijienr** [AITTSMD/MTCNN-Tensorflow#61]
Hi，Could u tell me what should I change,please?
First, I change the 'item' to 
`item = '%s/neg_%s.txt' % (net,net)`
`item = '%s/pos_%s.txt' % (net,net)`
`item = '%s/part_%s.txt' % (net,net)`
and the defult
`item = '%s/landmark_%s_aug.txt' % (net,net)`
,totally  4 times;

after that ,if i should change the _get_output_filename function  to get 4 tfrecords
if I should do that,
how I name these tfrecords and how I use them in next step?

**Comment by jerryhouuu** [comment]
@lijienr  I think, you should name like this. 
If I have any mistake, please tell me><
```
item = '%s/landmark_%s_aug.txt' % (net,net)
item = '%s/neg_%s.txt' % (net,net)
item = '%s/pos_%s.txt' % (net,net)
item = '%s/part_%s.txt' % (net,net)

return '%s/landmark_landmark.tfrecord' % (output_dir)
return '%s/neg_landmark.tfrecord' % (output_dir)
return '%s/pos_landmark.tfrecord' % (output_dir)
return '%s/part_landmark.tfrecord' % (output_dir)

```

**Comment by lijienr** [comment]
@jerryhouuu thx, I have finished as you suggested,
But, how to use thete tfrecords?

**Comment by jerryhouuu** [comment]
@lijienr Training PNet, RNet, or ONet 
`python train_model/train_PNet.py`

**Comment by lijienr** [comment]
@jerryhouuu  thx very much
