### ISSUE TITLE
gen_hard_example.py 没有任何地方反映了hard？

### ISSUE THREAD

**Issue by mit10000** [AITTSMD/MTCNN-Tensorflow#63]
请问在gen_hard_example.py里面，整个流程中为什么没有任何地方反映了什么是“hard”？程序里面挑选正，负sample全部是基于PNET输出的box和groundtruth 的IoU，没有地方反应loss的大小。一般理解的hard是不是指的是loss大的样本？
感谢您无私开源。

**Comment by AITTSMD** [comment]
@mit10000 hi,refer #22.
