### ISSUE TITLE
在test.py里面设置batch_size = [2048,256,16]跟 [1,1,1]时间不一样

### ISSUE THREAD

**Issue by tzhang2014** [AITTSMD/MTCNN-Tensorflow#69]
在test.py里面设置batch_size = [2048,256,16]跟 [1,1,1]时间不一样，测试的时候输入只有一张图哦，这两个时间相差很大哦，请问这样有问题吗？

**Comment by AITTSMD** [comment]
@tzhang2014 您可以按自己的需要，修改这些参数

**Comment by candy7393** [comment]
@AITTSMD 請問為什麼testing時須設定batch size?
想知道這個參數的功能，謝謝
