### ISSUE TITLE
Training Face Landmark Detection 

### ISSUE THREAD

**Issue by justyine** [AITTSMD/MTCNN-Tensorflow#7]
Hi @AITTSMD , I'm very new to python and I get this problem while running gen_landmark_aug_12.py. 
File "gen_landmark_aug_12.py", line 180, in <module>
    imgs,landmarks = GenerateData(train_txt, OUTPUT,net,argument=True)
  File "gen_landmark_aug_12.py", line 67, in GenerateData
    assert(img is not None)
AssertionError
May I know what causes this problem and how to solve it? 
Thank you.

**Comment by AITTSMD** [comment]
@justyine Hi, that means image can't be read correctly.Please check whether the path of image is right .

**Comment by justyine** [comment]
Thank you @AITTSMD . However, I couldn't find what's wrong.  
I followed your instruction by putting the downloaded landmark training data in the prepare_data folder. The path is as follow: prepare_data/train/lfw_5590  and
prepare_data/train/net_7876
Is that not correct?

**Comment by justyine** [comment]
@AITTSMD , much thanks. I just found out what was wrong.

**Comment by rashmisgh** [comment]
@AITTSMD Hey, I am also getting the same error how did you resolve that?
