### ISSUE TITLE
关键点样本扩充

### ISSUE THREAD

**Issue by stone226** [AITTSMD/MTCNN-Tensorflow#71]
在做关键点样本扩充的时候，随机裁剪得到扩充样本，是不是可能满足iou>0.65,但新的坐标框没有完全包括原来的关键点位置，也就是有关键点不在新裁剪框里面的情况。这个时候，不在里面的关键点，坐标计算为负值，也是可以的吗？

**Comment by AITTSMD** [comment]
@stone226  可以
