### ISSUE TITLE
训练多余5个关键点

### ISSUE THREAD

**Issue by stone226** [AITTSMD/MTCNN-Tensorflow#72]
想利用mtcnn训练多余5个点的关键点定位。
1 考虑先用其他算法比如sdm,将一些标注原本只有5点的数据，进行标注68点，然后再把这些样本利用mtcnn训练68,有什么需要注意的吗?
2 这里应该需要对标注的结果进行清理，去掉一些标注不准的样本，这个过程只能把关键点结果在图上可视化，然后显示出来人工进行查看吗？如果数据很大的情况下，这个工作量岂不是很大，有没什么其他更好方式？
3 如果输入是已经检测好的人脸，可以把onet的分类，回归分支去点，只训练关键点部分吗

**Comment by AITTSMD** [comment]
@stone226 hi,针对1,2.如果celeba只能用您说的方法标注，您还可以寻找其他的数据集。
3 可以的。最简单的方法，把的分类和回归的loss系数都设为0

**Comment by stone226** [comment]
针对3,我用onet结构，把分类和边框回归去掉，进训练关键点定位；我使用你的脚本gen_landmark_aug_48.py生成训练数据（17w多）；最后loss在0.05左右，但测试效果不怎么好，有什么建议吗

**Comment by AITTSMD** [comment]
@stone226 训练的时候也加上分类和边框回归（多任务协同作用），测试的时候只显示特征点。还有，我感觉如果真的想把特征点检测做好，直接这样回归是存在问题的（神经网络做回归效果不是那么好），可以参考其他特征点检测的论文。

**Comment by hfYin0769** [comment]
@ficha-ishida 你好，你说后面再接一个网络5个点拿出单个做训练是什么意思？是什么原理导致它比较准？

**Comment by SunshineJZJ** [comment]
@stone226 请问你68点的训练结果准确率怎么样啊？
