### ISSUE TITLE
cls_ohem计算标签的问题

### ISSUE THREAD

**Issue by Dawson-huang** [AITTSMD/MTCNN-Tensorflow#74]
您好，谢谢前辈开源您的代码！！
在下面这段代码中，您的做法是把标签为小于0的样本重新置标签为0，但是这样会不会增加了负样本的比例呢，会不会对数据平衡造成影响，还有您这样做的初衷是什么，还请前辈解惑，非常感谢！
def cls_ohem(cls_prob, label):
    zeros = tf.zeros_like(label)
    #label=-1 --> label=0net_factory
    label_filter_invalid = tf.where(tf.less(label,0), zeros, label)

**Comment by AITTSMD** [comment]
@Dawson-huang 你对这代码理解有误，cls_ohem的作用是筛选正样本中前70%的loss进行反向传播。可以参考 #22

**Comment by zezepi** [comment]
@Dawson-huang  同学你好，请问你之前mtcnn-caffe 中有训练出结果吗？ 那个cls_loss默认为0.693147的问题解决了吗？谢谢！

**Comment by Dawson-huang** [comment]
@zezepi 还没有训练出结果，cls_loss=0.693147是因为样本中的标签label=-1导致的，也就是说在训练pts的时候label=-1，此时cls训练得到的label就是等于-1，所以计算得到的cls_loss=0.693147（因为损失函数为SoftmaxWithLoss）
