### ISSUE TITLE
gen_imglist_rnet.py

### ISSUE THREAD

**Issue by nihao88** [AITTSMD/MTCNN-Tensorflow#8]
Dear AITTSMD, i've tried to strictly follow your instruction from readme file.
After gen_imglist_rnet.py of step 9 your instruction, I receive 
File "gen_imglist_rnet.py", line 18, in <module>
    with open(os.path.join(data_dir, '%s/pos_%s.txt' % (size, size)), 'r') as f:
IOError: [Errno 2] No such file or directory: './24/pos_24.txt'

looks smthing is missing. Could you please share a hint?

**Comment by albertmoss** [comment]
Same problem discovered.

**Comment by AITTSMD** [comment]
@nihao88 @albertmoss it seems that pos samples can't be generated correctly,check the code in **gen_hard_example**.

**Comment by nihao88** [comment]
Thanks, I will check, but I did not change this file.

**Comment by AITTSMD** [comment]
@nihao88 Sorry for the late reply.You only need to run gen_hard_example one time to generate training data for RNET.When finished,run gen_RNet_tfrecords multiple times to generate different parts of tfrecord.What are the input parameters refered?

**Comment by yungs2017** [comment]
@AITTSMD after run the 'gen_imglist_NET.py' file it will create a 'landmark_NET_train.txt' file, but I found this file was just using for get out the number of the training images, am i right?

**Comment by AITTSMD** [comment]
@yungs2017 yes~

**Comment by yungs2017** [comment]
Yeah~~ @AITTSMD

**Comment by ZhenyuYangGithub** [comment]
@nihao88 @albertmoss having the same issue here, have you guys found out where the problem was? @AITTSMD do you have any idea what caused the problem not generating pos sample?

**Comment by nihao88** [comment]
@ZhenyuYangGithub  The following procedure helps me to move forward:
till readme p7: ". After training **PNet**, run `gen_hard_example` to generate training data(Face Detection Part) for **RNet**." do as AITTSMD stated. do not run gen_hard_example, until you change ~line 220 of gen_hard_example.py to net = 'RNet'.

**Comment by ZhenyuYangGithub** [comment]
@nihao88 Thank you so much for your reply! It worked for me.
