### ISSUE TITLE
图像金字塔的问题

### ISSUE THREAD

**Issue by idchangyifan** [AITTSMD/MTCNN-Tensorflow#82]
您好，感谢您的代码！
请问图像金字塔究竟是干嘛用的呢？把同一张图片resize成了各种不同尺寸的大小，都用作训练数据吗？那为什么在test的过程中还有factor这个参数的存在呢？
看了很多博客还是不能解惑，新人，还望不吝赐教。
再次感谢！

**Comment by zHanami** [comment]
图像金字塔测试的时候用的，训练统一尺寸的。

**Comment by pkwangwanjun** [comment]
训练的时候，是随机裁剪，转为正方形再padding,再resize到12*12的大小，放进网络进行训练。最后推断阶段，使用图像金字塔来找候选区域，每个候选区域要根据scale大小映射回原图。
