### ISSUE TITLE
有关generate_bbox。　希望能得到你的答复

### ISSUE THREAD

**Issue by jiangtaoo2333** [AITTSMD/MTCNN-Tensorflow#83]
首先感谢您的开源   
 def generate_bbox(self, cls_map, reg, scale, threshold):
        """
            generate bbox from feature cls_map
        Parameters:
        ----------
            cls_map: numpy array , n x m 
                detect score for each position
            reg: numpy array , n x m x 4
                bbox
            scale: float number
                scale of this detection
            threshold: float number
                detect threshold
        Returns:
        -------
            bbox array
        """
        stride = 2
        #stride = 4
        cellsize = 12
        #cellsize = 25

        t_index = np.where(cls_map > threshold)

        # find nothing
        if t_index[0].size == 0:
            return np.array([])
        #offset
        dx1, dy1, dx2, dy2 = [reg[t_index[0], t_index[1], i] for i in range(4)]

        reg = np.array([dx1, dy1, dx2, dy2])
        score = cls_map[t_index[0], t_index[1]]
        boundingbox = np.vstack([np.round((stride * t_index[1]) / scale),
                                 np.round((stride * t_index[0]) / scale),
                                 np.round((stride * t_index[1] + cellsize) / scale),
                                 np.round((stride * t_index[0] + cellsize) / scale),
                                 score,
                                 reg])

通过百度知道，idx[0],idx[1],是分类得分大于threshold的cls_map的两个坐标。
那么stride * t_index[1]) / scale　代表什么意思。

**Comment by zHanami** [comment]
映射到原图的坐标。

**Comment by jiangtaoo2333** [comment]
＠zHanami 谢谢你的回复。
之前一直在想，公式是怎么映射到原图的。尤其是stride怎么来了。
终于在congweilin的项目里找到了答案。

**Comment by goodgoodstudyAI** [comment]
@jiangtaoo2333 请问stride怎么来的

**Comment by AITTSMD** [comment]
@goodgoodstudyAI 网络中每层stride的乘积
