### ISSUE TITLE
pre-trained模型是论文作者给的训练模型么？还是其他的

### ISSUE THREAD

**Issue by wadesunyang** [AITTSMD/MTCNN-Tensorflow#85]
您好，请问一下看到需要用到pre-trained模型，那这个是MTCNN作者提供的训练好的模型吗？如果是，那么在这效果比较好的模型上训练的原因是什么？如果做其他任务可以认为是微调，楼主可否介绍一下，谢谢。

**Comment by AITTSMD** [comment]
@wadesunyang 没用用到pre-trained模型，训练是从头开始的
