### ISSUE TITLE
BBox_utils.py中读取bbox框顺序问题

### ISSUE THREAD

**Issue by Chris-Bai** [AITTSMD/MTCNN-Tensorflow#87]
您好，最近在读您的程序，发现BBox_utils.py中是这样读取landmark标签文档中的bbox的。
```
        # bounding box, (x1, y1, x2, y2)
        #bbox = (components[1], components[2], components[3], components[4])
        bbox = (components[1], components[3], components[2], components[4]) 
 ```
而提供的trainImageList.txt中，是按照x1, y1, x2, y2的顺序给出的bbox，所以这里是不是应该把顺序换回去？

**Comment by MoExplorer** [comment]
trainImageList.txt中bbox顺序是x1,x2,y1,y2,你看下具体数值计算下就知道了

**Comment by MoExplorer** [comment]
@Chris-Bai trainImageList.txt中bbox顺序是x1,x2,y1,y2,你看下具体数值计算下就知道了

**Comment by Chris-Bai** [comment]
@MoExplorer 谢谢，刚看了下，确实是这样。按x1, y1, x2, y2画框就太小了。。
