### ISSUE TITLE
训练侧脸与多脸模型是否需要增加相应的样本

### ISSUE THREAD

**Issue by grainw** [AITTSMD/MTCNN-Tensorflow#89]
一张图片中有多个脸，训练时，样本中是否需要增加多张脸的照片。图片中有侧脸时，训练时样本中是否需要增加侧脸照片。

**Comment by AITTSMD** [comment]
@grainw 第一个问题不需要，本身PNet就是具于滑动窗口的，跟人脸个数没关系。第二个问题需要，总之训练样本越丰富越好。

**Comment by stillqueen** [comment]
请问呢楼主增加侧脸数据的时候是如何标landmark的，因为完全的侧脸眼睛和嘴角都会重合，这样其实只有3个点，那是不是将眼睛和嘴角标两次？ @grainw
