### ISSUE TITLE
gen_hard_example.py准备RNet训练数据，RNet的checkpint是不是应该删除掉

### ISSUE THREAD

**Issue by zkk0911** [AITTSMD/MTCNN-Tensorflow#93]
你好大神，Prepare train data阶段，第7步，为RNet准备训练数据的时候，运行gen_hard_example.py在144
RNet = Detector(R_Net, 24, batch_size[1], model_path[1]) 报错，提示相关的checkpoint文件不存在。

../data/MTCNN_model/RNet_landmark/RNet-14
assert  readstate, "the params dictionary is not valid"

而这里边的文件，我的理解应该是RNet训练时候生成的吧。所以我删除了你原来里边的几个文件， 就报这样的一个错。  这个142-151 代码是不是应该删除掉呢

**Comment by AITTSMD** [comment]
@zkk0911 oh，对的，RNet的训练，只需要训练好的PNet模型
