### ISSUE TITLE
运行 gen_Rnet_tfrecords,发生段错误（核心已转储）

### ISSUE THREAD

**Issue by codingwolfman** [AITTSMD/MTCNN-Tensorflow#99]
>> Converting image 178365/178366('---', '24/train_RNet_landmark_aug/71123.jpg')
>> Converting image 178366/178366('---', '24/train_RNet_landmark_aug/169046.jpg')
段错误 (核心已转储)

**Comment by AITTSMD** [comment]
@codingwolfman 没关系的，我也遇到这个错误，也不知道怎么解决~
